### ISSUE TITLE
Progress on Hedgecraft

### ISSUE THREAD

**Issue by andrewczgithub** [mayabenowitz/Hedgecraft#2]
Hi @mayabenowitz !!
Love the project really interesting.
Is there a part 2 in the works.
Best,
Andrew

**Comment by mayabenowitz** [comment]
Hi @andrewczgithub !

I'm working on part 2 albeit *very* slowly.

I'm starting a new job at a hedge fund this Monday and have been super busy going through their process and learning as much finance as possible before I start Monday. Hopefully, sometime soon I'll have more time to hammer out part 2!

**Comment by mayabenowitz** [comment]
@andrewczgithub , I would love for you to contribute to the project!

Converting the notebook to a library would be immensely helpful as my OOP skills aren't the best (to say the least).

**Comment by andrewczgithub** [comment]
Hi @mayabenowitz !!
I will do my best!
I have a few projects I'm working on at the moment, but in a few weeks i will make a solid effort :).
Its already an amazing project.
Will definitively give it a lot of time towards the end of the month.
Best,
Andrew
