### ISSUE TITLE
error with portfolio opt

### ISSUE THREAD

**Issue by andrewczgithub** [mayabenowitz/Hedgecraft#3]
Hi @mayabenowitz !!

I just getting some errors when i run through the notebook
![hedgecraft error](https://user-images.githubusercontent.com/46582583/64524454-d1efcf00-d341-11e9-810f-73ea50825f7c.png)

I was wondering if you could assist.
Many thanks,
Andrew

**Comment by mayabenowitz** [comment]
Hey @andrewczgithub 

Sorry for the late reply. Just fixed the bugs. 

The guy maintaining the PyPortfolioOpt lib decided to change some things.

**Comment by andrewczgithub** [comment]
Hi @mayabenowitz 
Thank you :)!!
I would be happy to help put this into a library.
I am just getting some errors running the notebook due to the PyPortfolioOpt api changes.

![hedgecraft error_1](https://user-images.githubusercontent.com/46582583/64903966-953b2380-d705-11e9-8a42-b898d3c4d734.png)

**Comment by mayabenowitz** [comment]
Hey @andrewczgithub !

Super sorry for the absurdly late merger on your pull request. Been swamped lately and haven't been on GitHub.

Thanks for fixing those bugs!
